ShiLv.WebUI/Controllers/HomeController.cs
using BLL;
using Models;
using ShiLv.WebUI.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ShiLv.WebUI.Controllers
{
    public class HomeController : Controller
    {
        NewsBLL newsBLL = new NewsBLL();
        ArtefactsBLL artefactsBLL = new ArtefactsBLL();
        EmergencysBLL emergencysBLL = new EmergencysBLL();
        public ActionResult Index()
        {
            HomeIndexViewModel hvm = new HomeIndexViewModel();
            hvm.Newlist1 = newsBLL.GetNewsForIndex();
            hvm.Artefacts1 = artefactsBLL.GetArtefactsForIndex();
            hvm.Emergencys1 = emergencysBLL.GetEmergencysForIndex();
            return View(hvm);
        }
        public ActionResult Test()
        {
            return View();
        }
    }
}

ShiLv.WebUI/Controllers/JunkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using BLL;
using System.Web.Script.Serialization;
using System.Text;
using PagedList;
using System.Text.RegularExpressions;

namespace ShiLv.WebUI.Controllers
{
    public class JunkController : Controller
    {
        private ShiLvDBEntities db = new ShiLvDBEntities();
        JunkBLL junkBLL = new JunkBLL();
        JunkTypeBLL junkTypeBLL = new JunkTypeBLL();
        // GET: Junk
        public ActionResult Index(int ID = 0)
        {
            List<JunkType> list = junkTypeBLL.GetJunkTypeForTop().ToList();
            list.Insert(0, new JunkType() { ID = 0, TypeName = "全部分类" });
            var selectList = new SelectList(list, "ID", "TypeName", ID);
            ViewBag.selectList = selectList;
            return View();
        }

        /// <summary>
        /// 通过查询条件获取垃圾的视图
        /// </summary>
        /// <param name="page"></param>
        /// <param name="typeID"></param>
        /// <param name="junkName"></param>
        /// <returns></returns>
        public ActionResult GetJunksByPage(int? page,int typeID = 0,string junkName = null)
        {
            
            IQueryable<Junks> junks = null;
            if (typeID == 0)
            {
                if (junkName != null)
                {
                    junks = db.Junks.OrderByDescending(p => p.ID).Where(p=>p.JunksName.Contains(junkName));
                }
                else
                {
                    junks = db.Junks.OrderByDescending(p => p.ID);
                }
            }
            else
            {
                if (junkName != null)
                {
                    junks = db.Junks.OrderByDescending(p => p.ID).Where(p => p.JunkTypeId == typeID && p.JunksName.Contains(junkName));
                }
                else
                {
                    junks = db.Junks.OrderByDescending(p => p.ID).Where(p => p.JunkTypeId == typeID);
                }
                
            }
            
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(junks.ToPagedList(pageNumber, pageSize));
        }
        
        public string SavePicture()
        {
            string result = "";
            HttpPostedFileBase imageName = Request.Files["image"];// 从前台获取文件
            string junkName = Request["junkName"];
            int junkType = Convert.ToInt32(Request["junkType"]);
            string userName = Request["userName"];
            string file = imageName.FileName;
            string fileFormat = file.Split('.')[file.Split('.').Length - 1]; // 以“.”截取，获取“.”后面的文件后缀
            Regex imageFormat = new Regex(@"^(bmp)|(png)|(gif)|(jpg)|(jpeg)"); // 验证文件后缀的表达式
            if (string.IsNullOrEmpty(file) || !imageFormat.IsMatch(fileFormat)) // 验证后缀，判断文件是否是所要上传的格式
            {
                result = "error";
            }
            else
            {
                string timeStamp = DateTime.Now.Ticks.ToString(); // 获取当前时间的string类型
                string firstFileName = timeStamp.Substring(0, timeStamp.Length - 4); // 通过截取获得文件名
                string imageStr = "Content/images/junk/"; // 获取保存图片的项目文件夹
                string uploadPath = Server.MapPath("~/" + imageStr); // 将项目路径与文件夹合并
                string pictureFormat = file.Split('.')[file.Split('.').Length - 1];// 设置文件格式
                string fileName = firstFileName + "." + fileFormat;// 设置完整（文件名+文件格式） 
                string saveFile = uploadPath + fileName;//文件路径
                imageName.SaveAs(saveFile);// 保存文件
                // 如果单单是上传，不用保存路径的话，下面这行代码就不需要写了！
                string image = "junk/" + fileName;// 设置数据库保存的路径
                Junks junk = new Junks()
                {
                    JunksName = junkName,
                    JunkImage = image,
                    JunkTypeId = junkType,
                    UserName = userName,
                    LikeNum = 0,
                    DislikeNum = 0
                };
                junkBLL.Add(junk);
                result = "success";
            }
            return result;
        }
    }
}

ShiLv.WebUI/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using BLL;

namespace ShiLv.WebUI.Controllers
{
    public class UserInfoController : Controller
    {
        UserBLL userInfoManager = new UserBLL();
        // GET: UserInfo
        public ActionResult Index()
        {
            return View();
        }
        #region 登录
        [HttpPost]
        public string Login([Bind(Include = "UserName,UserPwd")]string UserName,string UserPwd)
        {
            string data = null;
            try
            {
                var user = userInfoManager.Login(UserName, UserPwd);
                if (user != null)
                {
                    Session["UserName"] = user.UserName;
                    Session["UserImage"] = user.UserInfo.UserImage;
                    Session["NickName"] = user.UserInfo.NickName;
                    Session["UserCredit"] = user.UserInfo.UserCredit;
                    data = "登录成功";
                }
                else
                {
                    data = "登录失败";
                }
                return data;
            }
            catch (Exception)
            {
                data = "登录出错";
                return data;
            }
        }
        #endregion
        #region 注销
        [HttpPost]
        public string Logout()
        {
            Session["UserName"] = null;
            Session["UserImage"] = null;
            Session["NickName"] = null;
            Session["UserCredit"] = null;
            return "success";
        }
        #endregion
    }
}

ShiLv.WebUI/Controllers/WorkHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShiLv.WebUI.Models;
using BLL;
using Models;

namespace ShiLv.WebUI.Controllers
{
    public class WorkHomeController : Controller
    {
        // GET: WorkHome
        ArtefactsBLL artefactsBLL = new ArtefactsBLL();
        UserInfoBLL userInfoBLL = new UserInfoBLL();
        // GET: WorkHome
        public ActionResult Index()
        {
            WorkHomeViewModel hvm = new WorkHomeViewModel();
            hvm.HandArtefacts = artefactsBLL.GetTypeArtefactsForWorkHome(2, 10);
            hvm.NatureArtefacts = artefactsBLL.GetTypeArtefactsForWorkHome(1, 10);
            hvm.AnimalArtefacts = artefactsBLL.GetTypeArtefactsForWorkHome(3, 10);
            hvm.UserInfo = userInfoBLL.GetBeforeUploadArtefactsUsersForN(7);
            return View(hvm);
        }
        [HttpPost]
        public ActionResult GetWorkDetails(int ArtefactsID = 0)
        {
            DetailsWorkPartialViewModel dvm = new DetailsWorkPartialViewModel();
            if (ArtefactsID != 0)
            {
                dvm.Artefacts = artefactsBLL.GetArtefactByArtefactID(ArtefactsID);
                dvm.UserInfo = userInfoBLL.GetUserInfosByArtefactId(ArtefactsID);
                return PartialView(dvm);
            }
            else
            {
                return new EmptyResult();
            }
        }
    }
}

ShiLv.WebUI/Views/Home/Index.cshtml
@model ShiLv.WebUI.Models.HomeIndexViewModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>拾绿 - 环保人的聚集地</title>
    <link rel="stylesheet" href="~/Content/css/index.css">
    <link href="~/Content/css/iconfont.css" rel="stylesheet" />
    <link rel="shortcut icon" href="~/Content/images/favicon.ico">
</head>
<body>
    <div class="bg">
        <!-- 顶部导航+顶部logo -->
        <div class="page-top">
            <div class="top-nav">
                <div class="prompt"></div>
                <div class="left">
                    <a href="#" class="question">拾绿之家</a>
                    <a href="@Url.Action("Index","Junk")" class="junks">垃圾分类</a>
                    <a href="#" class="news">新闻资讯</a>
                    <a href="#" class="help">紧急求助</a>
                </div>
                <div class="right">
                    <a href="#" class="activity">拾绿商城</a>
                    <a href="@Url.Action("Index","WorkHome")" class="works">作品分享</a>
                    <a href="#" class="shop">参与活动</a>
                    <a href="#" class="post-bar">知识竞答</a>
                </div>
                <div class="hover-box"></div>
                <div class="click-hand"></div>
            </div>
            <div class="head-image">
                @if (Session["UserName"] != null)
                {
                    <a href="@Url.Action("Index", "UserInfo")"><img src="~/Content/images/@Session["UserImage"]" alt=""></a>
                    <div class="user-message">
                        <p class="name">@Session["NickName"]</p>
                        <p class="iconfont icon-jifen">&nbsp;&nbsp;@Session["UserCredit"]</p>
                        <div class="user-todo">
                            <a href="#">个人中心</a>
                            <a href="#">我的作品</a>
                            <a href="#">我的购物车</a>
                            <a class="logout" href="#">退出登录</a>
                        </div>
                    </div>
                }
                else
                {
                    <a href="@Url.Action("Index", "UserInfo")"><img src="~/Content/images/headImage1.png" alt=""></a>
                }
            </div>
            <div class="top-logo"><span>拾起一片绿</span><a href="@Url.Action("Index","Home")"><img src="~/Content/images/logo-border.png" alt="logo"></a><span>共迎一片天</span></div>
        </div>
        <!-- 轮播大图 -->
        <div class="banner">
            <ul class="banner-list">
                <li class="active"><img src="~/Content/images/banner/banner1.jpg" alt=""></li>
                <li><img src="~/Content/images/banner/banner2.jpg" alt=""></li>
                <li><img src="~/Content/images/banner/banner3.jpg" alt=""></li>
                <li><img src="~/Content/images/banner/banner4.jpg" alt=""></li>
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="page-list">
                <li class="active"></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div>
        <!-- 中间新闻内容区 -->
        <ul class="new-show">
            <div class="title">
                <img src="~/Content/images/index/title2.png" alt="">
                <p class="title-name">新闻资讯</p>
            </div>
            @foreach ( var item in Model.Newlist1)
            {
                <li>
                    <div class="new-title">@(item.Title)</div>
                    <p class="solid"></p>
                    <p class="content">
                        @(item.Content)
                    </p>
                    <a href="#" class="btn-more">查看详情</a>
                </li>
            }
        </ul>
        <!-- 中间手工区 -->
        <ul class="work-show">
            <div class="title">
                <img src="~/Content/images/index/title1.png" alt="">
                <p class="title-name">优秀手工</p>
            </div>
            @foreach (var item in Model.Artefacts1)
            {
                <li><img src="~/Content/images/@(item.ArtefactImage)" alt=""></li>
            }
        </ul>
        <!-- 中间紧急求助区 -->
        <div class="please-help">
            <div class="title">
                <img src="~/Content/images/index/title3.png" alt="">
                <p class="title-name">求助地区</p>
            </div>
            <ul class="for-help">
                @for (int i = 0; i < 8; i++)
                {
                    <li><a href="#">@Model.Emergencys1.ElementAt(i).EmerPlace</a></li>
                }
            </ul>
            <ul class="for-help">
                @for (int i = 8; i < 15; i++)
                {
                    <li><a href="#">@Model.Emergencys1.ElementAt(i).EmerPlace</a></li>
                }
                <li><a href="#">更多 &gt;</a></li>
            </ul>
        </div>
        <!-- 底部导航 -->
        <div class="page-bottom">
            <div class="nr">
                <p class="title">信息阅览</p>
                <ul class="message">
                    <li><a href="#">作品分享</a></li>
                    <li><a href="#">新闻资讯</a></li>
                    <li><a href="#">紧急求助</a></li>
                    <li><a href="#">垃圾分类</a></li>
                </ul>
            </div>
            <div class="nr">
                <p class="title">功能使用</p>
                <ul class="message">
                    <li><a href="#">拾绿商城</a></li>
                    <li><a href="#">拾绿之家</a></li>
                    <li><a href="#">参与活动</a></li>
                    <li><a href="#">知识竞答</a></li>
                </ul>
            </div>
            <div class="bottom-logo">
                <img src="~/Content/images/logo-noborder.png" alt="">
            </div>
            <div class="friends">
                <p class="title">友情链接</p>
                <ul class="message">
                    <li><a href="http://www.chinaenvironment.com/">环保网</a></li>
                    <li><a href="http://www.mee.gov.cn/">环保部</a></li>
                    <li><a href="http://www.csapa.org/index.jhtml">小动物保护协会</a></li>
                    <li><a href="http://www.plantprotection.ac.cn/ch/index.aspx">植物保护</a></li>
                </ul>
            </div>
            <div class="talk-us">
                <p class="title">联系我们</p>
                <ul class="message">
                    <li>电子邮箱</li>
                    <li>腾讯 Q Q</li>
                    <li>微信公众号</li>
                    <li>新浪微博</li>
                </ul>
            </div>
        </div>
        <!-- 底部页脚 -->
        <div class="page-foot">
            <span>地址：江西师范大学瑶湖校区先骕楼</span>
            <a href="#">后台入口</a>
            <span>指导老师：曾雅琳</span>
            <span>版权所有&copy;江西师范大学软件学院</span>
        </div>
    </div>
    <div class="to-up-page"><img src="~/Content/images/to-up-page.png" /></div>
    <script src="~/Content/js/jquery.js"></script>
    <script src="~/Content/js/index.js"></script>
</body>
</html>

ShiLv.WebUI/Views/Home/Test.cshtml
@{
    ViewBag.Title = "Test";
}

<br />
<br />
<br />
<br />
<br />
<br />